name: TTT
version: 1.0.0
author: Moritz Ruth
api-version: "1.15"
main: de.moritzruth.spigot_ttt.TTTPlugin
depend:
  - ProtocolLib

commands:
  voting:
    usage: /voting ['cancel']
    permission: ttt.voting
    description: Start (or cancel) the map voting

  start:
    usage: /start
    permission: ttt.start
    description: Start the TTT game

  abort:
    usage: /abort
    permission: ttt.abort
    description: Go back to the lobby world and abort the TTT game, if it is running

  additemspawn:
    usage: /additemspawn
    permission: ttt.additemspawn
    description: Add an item spawn

  revive:
    usage: /revive [player] ['here']
    permission: ttt.revive
    description: Revive yourself or another player at the world spawn or at your location

  info:
    usage: /info [player]
    permission: ttt.info
    description: Show information about all players or a specific player

  resourcepack:
    usage: /rp
    description: Start the download of the TTT resourcepack, required for sounds
    aliases:
      - rp
      - resources

  reloadtttconfig:
    usage: /rt
    description: Reload the configuration of TTT
    permission: ttt.reload
    aliases:
      - rt
